[FOUR-4933] When clicking on Flow for the first time, console.error appears in the console
ProcessMaker/modeler pull request #1408
Opened 2022-01-14 16:28 UTC by josechirivella

## Issue & Reproduction Steps
When clicking on a Flow for the first time, the console would error out saying that the highlight watcher has encountered an issue when checking the length of a null property.
@caleeli pointed out in the ticket that this was working until a dependency bump from 3.2 to 3.4.x for `joint-js`

* Create a Start event
* Create a Task
* Click on the Start Event
* Click flow and click the task
* Click the Flow or link between the two

Expected behavior: 
No console errors shouldn't be shown when clicking the Flow

Actual behavior: 
Console.error showing in the console

## Solution
- Removed the `showTools()` call. I'm guessing the showTools property is not available or could be a race condition. But nevertheless, upon removing, on clicking, it still shows the tools so 🤷🏻 

## How to Test
Test the steps above

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-4933

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-01-14 20:08 UTC, caleeli requested changes
When `showTools()` is removed, the Link tools (adding vertices, removing vertices, moving segments) are not displayed.
https://github.com/ProcessMaker/modeler/pull/332

2022-01-14 20:19 UTC, caleeli commented
https://user-images.githubusercontent.com/8028650/149579752-8aea944a-5a7a-48f8-804e-18f826b98022.mp4

2022-01-18 16:45 UTC, josechirivella commented
@caleeli Updated the description with the new changes

2022-01-18 20:37 UTC, marcoAntonioNina approved these changes

2022-01-28 18:35 UTC, ryancooley approved these changes

2022-01-28 18:35 UTC, merged