Bugfix/FOUR-5566: Modeler - When 2 nodes have the same id, modeler starts to unresponsive
ProcessMaker/modeler pull request #1436
Opened 2022-04-08 17:49 UTC by agustinbusso

## Issue & Reproduction Steps
Steps to Reproduce:
- Create a new Process or edit an existing one. 
- Add two tasks to the process
- From the Advanced settings panel, edit the Node Identifier option and provide a non-unique identifier.

Current Behavior:
Modeler starts to get unresponsive
No warning that something is wrong is displayed

## Solution
- Added a custom component for Node identifier input, to validate if new value of current node id is unique in store.state.nodes list
- If new id value exists, do not set the new Node identifier value, to avoid unresponsive behavior.
- Show a validation error when Node ID is not unique

## How to Test
Test the steps above

**IMPORTANT:** 
- Please test it with all modeler elements (start event, end event, intermediate event, task, gateways, and also with all elements for each enterprise package)
- Test also changing another properties in the inspector for the elements (as name, node identifier, etc) and check if values are correctly modified.

**Working video**

https://user-images.githubusercontent.com/90727999/162494741-3d75e7e0-4efd-4fd2-b520-066dbdd05931.mov

## Related Tickets & Packages
- [FOUR-5566](https://processmaker.atlassian.net/browse/FOUR-5566)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-04-12 14:37 UTC, caleeli requested changes
The change was not applied to the packages: DocuSign, Send Email, DataConnector.

https://user-images.githubusercontent.com/8028650/162987335-3eec9b6e-3b4a-4072-8017-0fbef4db3925.mp4

2022-04-13 13:47 UTC, agustinbusso commented
Added validation for connector-docusign, connector-send-email and package-data-sources

https://user-images.githubusercontent.com/90727999/163194860-f5d8dc2a-4c3a-44ff-a676-6651abb90306.mov

2022-04-14 19:54 UTC, caleeli approved these changes

2022-04-14 20:04 UTC, caleeli approved these changes

2022-04-22 05:10 UTC, ryancooley approved these changes

2022-04-22 05:10 UTC, merged