Fix invalid connection of DataInput
ProcessMaker/modeler pull request #1498
Opened 2023-04-19 13:39 UTC by caleeli

## Issue & Reproduction Steps
Invalid connections from DataStore/DataObject to EndEvents

Expected behavior: 
Do not allow invalid connections from DataStore/DataObject to EndEvents

Actual behavior: 
User can create invalid connections from DataStore/DataObject to EndEvents

## Solution
- Validate connections from DataStore/DataObject to EndEvents

## How to Test
- Create a process
- Add a DataStore and an EndEvent
- Try to connect them in any direction

![image](https://user-images.githubusercontent.com/8028650/233092712-871fbf40-1f0c-4726-b3ce-8c26443827c5.png)
It should not be allowed.

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-7996

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-04-19 13:58 UTC, TinCodes approved these changes

2023-04-19 14:49 UTC, ana-mauricio commented
The following combinations were made : 
**START EVENT**
1. Data Store -> Start Event PASSED
2. Start Event -> Data Store ERROR 
![image](https://user-images.githubusercontent.com/21198450/233110718-7396a82f-f2ce-4e99-892f-fe7f076c199b.png)

**INTERMEDIATE EVENT**
3. Data Store -> Intermediate Event PASSED
4. Intermediate Event -> Data Store ERROR
![image](https://user-images.githubusercontent.com/21198450/233111300-15818833-eb17-4d21-a839-27f1209af4a8.png)

**END EVENT**
5. Data Store -> End Event PASSED

**TASK FORM** 
7. Data Store -> Task ERROR, the selection is not cloned and an error appears in the console ![image](https://user-images.githubusercontent.com/21198450/233112209-17b0d0c7-c708-4f5e-92f3-3989a00b52fe.png)
8. Task -> Data Store ERROR
![image](https://user-images.githubusercontent.com/21198450/233113071-ef737eee-0aa2-4637-85c0-28e23d6db8af.png)

**GATEWAY**
9. Data Store -> Gateway PASSED
10. Gateway -> Data Store ERROR
![image](https://user-images.githubusercontent.com/21198450/233112459-ae28dac0-e298-4932-92cd-e54f603bc35d.png)

@caleeli

2023-04-19 19:56 UTC, josechirivella approved these changes

2023-04-20 12:24 UTC, caleeli commented
@ana-mauricio thanks for your feedback. To complete the definition this diagram shows all the valid connections between DataStore and DataObject with other elements:

![image](https://user-images.githubusercontent.com/8028650/233364605-a36dc8bd-ae6e-4ee2-b127-67332e2c990e.png)

Also take in count that this ticket did not focus on clone elements (these other tickets will fix the problems when cloning DataStore/DataObjects https://processmaker.atlassian.net/browse/FOUR-7958 and https://processmaker.atlassian.net/browse/FOUR-7959)

2023-04-20 13:58 UTC, josechirivella requested changes

2023-04-20 13:58 UTC, josechirivella commented on src/components/nodes/genericFlow/DataOutputAssociation.js
> +    return false;
```suggestion
    return !!(targetIsDataObject && dataObjectValidSources.includes(sourceType));
```

2023-04-20 14:08 UTC, ana-mauricio reviewed
According to the possible conditions in the diagram. The following observations are made:
1. It should not be possible to connect a (Data Store | Data Object) with a gateway
![image](https://user-images.githubusercontent.com/21198450/233389825-f7927522-dd70-4666-9db4-cba941ae2eb0.png)
![image](https://user-images.githubusercontent.com/21198450/233389956-ef994b92-2576-4152-973e-2651bbd82660.png)
2. It should not be possible to connect Data store with start event 
![image](https://user-images.githubusercontent.com/21198450/233390615-020f8ccf-59f0-426b-a671-a79c12d10866.png)
3. It should not be possible to connect Data store with INtermediate event 
![image](https://user-images.githubusercontent.com/21198450/233390795-ae06aa75-2fd7-45dc-b4a5-79148aa5430f.png)
4. In the image it shows that Data object -> End Event is possible, but in the diagrammer this is not.
![image](https://user-images.githubusercontent.com/21198450/233391533-d684db9c-10ff-4e4a-975c-8ce5e8a9fb45.png)
5. In the same case to Data Object -> Start Event and Data object -> INtermediate Event

![image](https://user-images.githubusercontent.com/21198450/233392036-7a00d791-f840-4482-908f-51c8130a9af3.png)

@caleeli

2023-04-20 16:03 UTC, caleeli commented on src/components/nodes/genericFlow/DataOutputAssociation.js
> +    return false;
done

2023-04-20 16:03 UTC, caleeli commented on src/components/nodes/dataInputAssociation/dataInputAssociation.vue
> +      return false;
done

2023-04-20 22:01 UTC, ana-mauricio reviewed
The fix is correct 
@caleeli

2023-04-20 22:02 UTC, ana-mauricio approved these changes

2023-04-21 00:09 UTC, merged