FOUR-8405: Bottom Controls-New Control Rail
ProcessMaker/modeler pull request #1543
Opened 2023-05-09 18:10 UTC by rodriquelca

## Issue & Reproduction Steps

Expected behavior: 
As a user I want the bottom controls/BPMN elements to have new control rail, so the we follow a defined UX
Actual behavior: 

## Solution
- the layouts and csss was improved

https://github.com/ProcessMaker/modeler/assets/1401911/b03df470-f221-4a8b-b450-6903763a12c2

## How to Test
Test the steps above
- run mpm install
- open de designer

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-8405

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy

2023-05-09 20:06 UTC, josechirivella requested changes

2023-05-09 20:06 UTC, josechirivella commented on src/components/railBottom/controls/SubmenuPopper/SubmenuPopper.vue
> +    };
if data is not being used, delete

2023-05-09 20:06 UTC, josechirivella commented on src/components/railBottom/RailBottom.vue
> +  },
```suggestion
  props: ['paperManager'],
```
since we are not checking for the prop type or anything, just declare it like this

2023-05-09 20:06 UTC, josechirivella commented on src/components/railBottom/zoomControl/ZoomControl.vue
> +      @click="paperManager.scale = paperManager.scale.sx + scaleStep"
set this in a method

2023-05-09 20:06 UTC, josechirivella commented on src/components/railBottom/zoomControl/ZoomControl.vue
> +      @click="paperManager.scale = Math.max(minimumScale, paperManager.scale.sx -= scaleStep)"
set this in a method

2023-05-09 20:06 UTC, josechirivella commented on src/components/railBottom/zoomControl/ZoomControl.vue
> +  },
```suggestion
  props: ['paperManager']
```

2023-05-09 20:21 UTC, pmkerberos commented
QA server was successfully deployed https://ci-9c26036e17.eng.processmaker.net

2023-05-10 14:27 UTC, pmkerberos commented
QA server was successfully deployed https://ci-9c26036e17.eng.processmaker.net

2023-05-10 16:16 UTC, josechirivella commented on src/components/railBottom/zoomControl/ZoomControl.vue
> +      {{ Math.round(paperManager.scale.sx*100) }}%
this could be a computed property

2023-05-10 16:16 UTC, josechirivella approved these changes

2023-05-11 17:42 UTC, pmkerberos commented
QA server was successfully deployed https://ci-9c26036e17.eng.processmaker.net

2023-05-11 18:46 UTC, pmkerberos commented
QA server was successfully deployed https://ci-9c26036e17.eng.processmaker.net

2023-05-11 18:53 UTC, pmkerberos commented
QA server was successfully deployed https://ci-9c26036e17.eng.processmaker.net

2023-05-12 14:24 UTC, pmkerberos commented
QA server was successfully deployed https://ci-9c26036e17.eng.processmaker.net

2023-05-12 14:24 UTC, pmkerberos commented
QA server was successfully deployed https://ci-9c26036e17.eng.processmaker.net

2023-05-12 15:29 UTC, merged