FOUR-8393: Elements are moved out of the Pool container
ProcessMaker/modeler pull request #1561
Opened 2023-05-23 15:23 UTC by rodriquelca

## Issue & Reproduction Steps

Expected behavior: 
The elements should not be moved out of the Pool container

Actual behavior: 
The elements copied are moved  out of the Pool container
## Solution
- saveState logic was moved to the selection and drag side
- flows into container will be updated after the stopDrag

https://github.com/ProcessMaker/modeler/assets/1401911/518f1eee-830a-4383-8cd1-aa320660d82b

https://github.com/ProcessMaker/modeler/assets/1401911/95964ec0-f610-4ace-8343-dd46e69bc6f8

## How to Test
Test the steps above
- npm install
- npm run serve
- check the steps in the related tickets

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-8393
- https://processmaker.atlassian.net/browse/FOUR-8651

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-05-23 15:47 UTC, josechirivella approved these changes

2023-05-23 17:04 UTC, TinCodes approved these changes

2023-05-24 17:58 UTC, caleeli approved these changes
Excelente change!

2023-05-24 18:46 UTC, ana-mauricio requested changes
The following observations were found in thi PR:
**Regression tickets:**

1. the elements go out of the pool with two pools https://processmaker.atlassian.net/browse/FOUR-8677

**Reopen tickets**
The following ticket was replicated again in this pool

1. https://processmaker.atlassian.net/browse/FOUR-7809

**New ticket no regressions**
The following tickets are related to selection of flows with boundary events were identified during the revision

1. https://processmaker.atlassian.net/browse/FOUR-8679
2. https://processmaker.atlassian.net/browse/FOUR-8680
@rodriquelca @boliviacoca

2023-05-26 21:36 UTC, ana-mauricio commented
The PR is approved the following errors were fixed 
 - https://processmaker.atlassian.net/browse/FOUR-8677 Fixed
 - https://processmaker.atlassian.net/browse/FOUR-7809 Fixed
 - https://processmaker.atlassian.net/browse/FOUR-8689 Fixed
 - https://processmaker.atlassian.net/browse/FOUR-8675 Fixed
 - https://processmaker.atlassian.net/browse/FOUR-8674 Fixed
 - https://processmaker.atlassian.net/browse/FOUR-8393 Fixed
 - https://processmaker.atlassian.net/browse/FOUR-8651 Fixed
@rodriquelca @boliviacoca

2023-05-26 21:37 UTC, ana-mauricio approved these changes

2023-05-29 17:40 UTC, danloa commented on src/components/crown/crownConfig/crownConfig.vue
> -      this.$emit('save-state');
is it necessary to remove this $emit? It looks like the undo for actions started from the crow can be affected. Can you explain?

2023-05-29 18:53 UTC, TinCodes commented on src/components/nodes/genericFlow/SequenceFlow.js
> +
Remove whitespace

2023-05-29 18:53 UTC, TinCodes commented on src/components/nodes/boundaryEvent/boundaryEvent.vue
> -        this.$emit('save-state');
Does this cause the undo/redo to ignore when a boundary event is created and attached?

2023-05-29 19:00 UTC, danloa approved these changes

2023-05-29 20:13 UTC, boliviacoca approved these changes

2023-05-30 16:27 UTC, caleeli commented
There is still an issue with the anchor points pools and copy paste

[ScreenMoveAnchorPointsCopyPaste.webm](https://github.com/ProcessMaker/modeler/assets/8028650/001ce791-a6b0-438c-b4e4-a95cd45cf7b4)

2023-05-30 20:05 UTC, rodriquelca commented
added a validation to prevent waypoint movements in copy/paste actions

2023-05-30 20:37 UTC, josechirivella commented on src/components/modeler/Selection.vue
> +      if (elements.length > 0) {
```suggestion
      if (elements && elements.length > 0) {
```

2023-05-31 15:23 UTC, josechirivella approved these changes

2023-05-31 21:20 UTC, merged