FOUR-9946: Create client socket IO
ProcessMaker/modeler pull request #1656
Opened 2023-08-23 17:59 UTC by rodriquelca

## Issue & Reproduction Steps

Expected behavior: 
have a socketIO client 
Actual behavior: 
n/a
## Solution
- socket basic client was created

## How to Test
1. import the client 
import MultiplayerClient from '@/clients/multiplayerClient.js';
2. send event to the socket server 
```
// Emit the mouse position to the server
  this.multiplayerClient.sendEvent({
    type: 'mouseMove',
    data,
  });
```
3. Register Events
```
 this.multiplayerClient.addEventListener({
      type: 'mousePosition',
      callback: (position) => {
          //TODO mouse position logic
      }
 });
```

## Related Tickets & Packages
- 

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-08-24 13:06 UTC, devmiguelangel commented on src/clients/multiplayerClient.js
> +  ENDPOINT = 'localhost:3000'
Perhaps It can be obtained from an env variable in the next features

2023-08-24 13:06 UTC, devmiguelangel approved these changes

2023-08-24 18:09 UTC, danloa requested changes

2023-08-24 18:09 UTC, danloa commented on src/clients/multiplayerClient.js
> +  ENDPOINT = 'localhost:3000'
Yes, please add at least a TODO so we don't forget to add a constant or setting value

2023-08-25 19:26 UTC, danloa approved these changes

2023-08-25 19:26 UTC, merged