FOUR-10195: Collaborative UI components
ProcessMaker/modeler pull request #1668
Opened 2023-09-13 13:24 UTC by rodriquelca

## Issue & Reproduction Steps

Expected behavior: 
as a developer I want to have multiplayer avatar and client cursor component 
Actual behavior: 
n/a
## Solution
two new components was added:
- add multiplayer avatar
- add client cursor
![avatar-curso](https://github.com/ProcessMaker/modeler/assets/1401911/1029e40a-1eee-4ae3-872c-01c56162c2b0)

## How to Test
Test the steps above
- go to standalone modeler 
- npm run serve
## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-10195

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-09-13 17:35 UTC, josechirivella requested changes

2023-09-13 17:35 UTC, josechirivella commented on src/components/modeler/Modeler.vue
> +      :key="index"
do players have an id? Use that instead

2023-09-13 17:35 UTC, josechirivella commented on src/components/topRail/multiplayerViewUsers/MultiplayerViewUsers.vue
> +      required: [],
you mean `required: true`

2023-09-13 17:35 UTC, josechirivella commented on src/components/topRail/multiplayerViewUsers/MultiplayerViewUsers.vue
> +      <Avatar :badgeBackgroundColor="item.color" :imgSrc= "item.imgSrc" :userName="item.name" v-bind:key="index"/>
same here. the `:key` should be the player id if available

2023-09-13 17:35 UTC, josechirivella commented on src/components/topRail/multiplayerViewUsers/avatar/Avatar.vue
> +    getInitials(name= '') {
```suggestion
    getInitials(name = '') {
```

2023-09-14 13:59 UTC, tokensPM commented
QA server was successfully deployed https://ci-5e6aee50e9.eng.processmaker.net

2023-09-14 15:14 UTC, tokensPM commented
QA server was successfully deployed https://ci-5e6aee50e9.eng.processmaker.net

2023-09-14 16:49 UTC, josechirivella approved these changes

2023-09-14 19:29 UTC, devmiguelangel approved these changes

2023-09-15 01:01 UTC, merged