FOUR-10505: Create client to remove elements
ProcessMaker/modeler pull request #1672
Opened 2023-09-18 19:23 UTC by rodriquelca

## Issue & Reproduction Steps

Expected behavior: 
As a developer I want a client to remove a node
Actual behavior: 
there is no a remove modeler-cli
## Solution
- remove node client was added

## How to Test
Test the steps above

https://github.com/ProcessMaker/modeler/assets/1401911/7db6a559-4314-465e-a2d5-071c632f17e2

1. npm install
2. npm run dev
3. HOST=localhost PORT=1234 npx y-websocket
4. set the property isMultiplayer to true into Modeler.vue file

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-10505

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-09-18 20:31 UTC, josechirivella commented on src/multiplayer/multiplayer.js
> +    const wsProvider = new WebsocketProvider('ws://localhost:1234', this.room.getRoom(), this.ydoc);
if it is possible, can this read from an .env file?

2023-09-18 20:31 UTC, josechirivella commented on src/multiplayer/multiplayer.js
> +    this.room = new Room('room-' + window.ProcessMaker.modeler.process.id);
```suggestion
    this.room = new Room(`room-${window.ProcessMaker.modeler.process.id}`);
```

2023-09-18 20:33 UTC, josechirivella requested changes
some nit pick comments but one suggestion

2023-09-18 20:33 UTC, josechirivella commented on src/multiplayer/multiplayer.js
> +  }
Wouldn't a findIndex be cleaner and faster?

2023-09-18 20:33 UTC, josechirivella commented on src/multiplayer/room.js
> +
```suggestion
```

2023-09-21 17:32 UTC, danloa approved these changes

2023-09-21 18:57 UTC, josechirivella commented on package.json
> +    "serve": "vue-cli-service serve --mode development",
well, technically, serve is always on development mode

2023-09-21 18:57 UTC, josechirivella approved these changes

2023-09-22 15:28 UTC, merged