Feature/FOUR-10790: Multiplayer support for boundary events
ProcessMaker/modeler pull request #1689
Opened 2023-10-12 14:11 UTC by agustinbusso

**Add support for Boundary events in collaborative modeler**

- Handle boundary creation
- Handle position change when moving the parent task
- Handle position change when moving the boundary

https://github.com/ProcessMaker/modeler/assets/90727999/eee16f33-c4a5-4496-88b9-f6a086dedde6

2023-10-12 20:24 UTC, josechirivella requested changes

2023-10-12 20:24 UTC, josechirivella commented on src/components/modeler/Selection.vue
> +      const boundaryNodes = window.ProcessMaker.$modeler.nodes.filter(node => boundaryEventTypes.includes(node.type));
Uhmm I'm pretty sure this nodes are available in the store?
Also, `window.ProcessMaker.$modeler` is a ref I believe also. Can you confirm @rodriquelca

2023-10-12 20:24 UTC, josechirivella commented on src/components/nodes/boundaryEvent/boundaryEvent.vue
> +      const { paper } = window.ProcessMaker.$modeler;
same goes here, the paper should be available in the store or ref

2023-10-12 20:24 UTC, josechirivella commented on src/multiplayer/multiplayer.js
> +    let node = this.getNodeById(data.attachedToRefId);
```suggestion
    const node = this.getNodeById(data.attachedToRefId);
```

2023-10-12 20:24 UTC, josechirivella commented on src/portsUtils.js
> +
remove

2023-10-12 20:24 UTC, josechirivella commented on src/multiplayer/multiplayer.js
> +        else {
```suggestion
        } else {
```

2023-10-20 14:18 UTC, rodriquelca approved these changes

2023-10-20 15:31 UTC, josechirivella approved these changes

2023-10-23 15:39 UTC, devmiguelangel approved these changes

2023-10-24 02:39 UTC, merged