Feature/four-11171 notification dot on modeler elements
ProcessMaker/modeler pull request #1697
Opened 2023-10-18 19:58 UTC by gustavobascope

## Issue & Reproduction Steps
see a notification dot on modeler elements when a comment exists for that element

## Solution
Added a dot on modeler elements when a comment exists for that element

## How to Test
Comment  a modeler process tagging elements

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-11171

2023-10-20 21:23 UTC, boliviacoca approved these changes

2023-10-23 16:56 UTC, josechirivella requested changes

2023-10-23 16:56 UTC, josechirivella commented on src/components/modeler/Modeler.vue
> +      if (window.ProcessMaker && window.ProcessMaker.EventBus) {
```suggestion
      if (window.ProcessMaker?.EventBus) {
```

2023-10-23 16:56 UTC, josechirivella commented on src/components/modeler/Selection.vue
> +      this.selected = this.selected.filter(shape => { return shape.model.get('type') !== 'basic.Circle';});
```suggestion
      this.selected = this.selected.filter(shape => shape.model.get('type') !== 'basic.Circle');
```

2023-10-26 00:47 UTC, nolanpro commented
Closing in favor of https://github.com/ProcessMaker/modeler/pull/1701/files

2023-10-26 00:47 UTC, closed without merging