Feature/four 10804
ProcessMaker/modeler pull request #1702
Opened 2023-10-25 21:05 UTC by rodriquelca

## Issue & Reproduction Steps

Expected behavior: 
Improve multiplayer inspector

Actual behavior: 
n/a
## Solution
- multiplayer feature was enabled for inspector
- fix shape transformation

## How to Test
Test the steps above
1. npm run serve
2. open two instances of the modeler
4. run realtime microservice (branch: feature/FOUR-10805 )
3. edit a inspector property

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-10804
- https://processmaker.atlassian.net/browse/FOUR-10805

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-10-26 15:37 UTC, josechirivella requested changes
looks good except one typo

2023-10-26 15:37 UTC, josechirivella commented on src/multiplayer/multiplayer.js
> +    // validate repeated sahpes
```suggestion
    // validate repeated shapes
```

2023-10-26 16:33 UTC, josechirivella approved these changes

2023-10-27 14:19 UTC, danloa approved these changes

2023-10-27 20:58 UTC, merged